// Code generated by mkstdlib.go. DO NOT EDIT.

package imports

var stdlib = map[string]string{

	"unsafe.Alignof":       "unsafe",
	"unsafe.ArbitraryType": "unsafe",
	"unsafe.Offsetof":      "unsafe",
	"unsafe.Pointer":       "unsafe",
	"unsafe.Sizeof":        "unsafe",
}
