---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU service in a specific environment containing an ALB target group with ECS service and task definition
Parameters:
  ServiceName:
    Type: String
    Description: Name of service
  ImageUrl:
    Type: String
    Description: Docker Image URL
  ServicePort:
    Type: String
    Description: Port exposed in service
    Default: '8080'
  ServiceHealthEndpoint:
    Type: String
    Description: Endpoint to test service health
    Default: '/health'
  ServiceCpu:
    Type: String
    Description: CPU units to reserve for container
    Default: '10'
  ServiceMemory:
    Type: String
    Description: Memory to allocate to contianer (in MiB)
    Default: '300'
  ServiceDesiredCount:
    Type: Number
    Default: '2'
    Description: Number of containers to launch in your ECS service.
  PathPattern:
    Type: CommaDelimitedList
    Description: List of paths to route to the service.
    Default: ''
  ListenerRulePriority:
    Type: Number
    Description: The priority of the rule being added to the listener
    Default: '1'
  VpcId:
    Type: String
    Description: Name of the value to import for the VpcId
  EcsCluster:
    Type: String
    Description: Name of the value to import for Ecs Cluster to deploy to.
  EcsElbHttpListenerArn:
    Type: String
    Description: Name of the value to import for the Arn of the ELB listener to attach the target group to.
  EcsElbHttpsListenerArn:
    Type: String
    Description: Name of the value to import for the Arn of the ELB listener to attach the target group to.
    Default: ''
  DatabaseName:
    Type: String
    Description: Name of database
    Default: ""
  DatabaseMasterUsername:
    Type: String
    Description: Username of database
    Default: ""
  DatabaseMasterPassword:
    Type: String
    NoEcho: true
    Description: Password of database
    Default: ""
  DatabaseEndpointAddress:
    Type: String
    Description: Endpoint address of database
    Default: ""
  DatabaseEndpointPort:
    Type: String
    Description: Endpoint port of database
    Default: ""
Conditions:
  HasPathPattern:
    "Fn::Not":
      - "Fn::Equals":
        - "Fn::Join":
          - ''
          - !Ref PathPattern
        - ''
  HasElbHttpListener:
    "Fn::And":
    - "Fn::Not":
       - "Fn::Equals":
         - !Sub ${EcsElbHttpListenerArn}
         - ''
    - !Condition HasPathPattern
  HasElbHttpsListener:
    "Fn::And":
    - "Fn::Not":
       - "Fn::Equals":
         - !Sub ${EcsElbHttpsListenerArn}
         - ''
    - !Condition HasPathPattern

Resources:
  EcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue: !Sub ${EcsCluster}
      DesiredCount: !Ref ServiceDesiredCount
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      LoadBalancers:
        - Fn::If:
          - HasPathPattern
          - ContainerName: !Ref ServiceName
            ContainerPort: !Ref ServicePort
            TargetGroupArn: !Ref EcsElbTargetGroup
          - !Ref AWS::NoValue
      Role:
        Fn::If:
          - HasPathPattern
          - !Ref EcsServiceRole
          - !Ref AWS::NoValue
      TaskDefinition: !Ref MicroserviceTaskDefinition
  EcsServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ec2:Describe*
            - elasticloadbalancing:Describe*
            Resource: "*"
          - Effect: Allow
            Action:
            - elasticloadbalancing:DeregisterTargets
            - elasticloadbalancing:DescribeTargetGroups
            - elasticloadbalancing:DescribeTargetHealth
            - elasticloadbalancing:RegisterTargets
            Resource: "*"
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ecs-task
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecs:DescribeTasks
            Resource: "*"
  ServiceLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Ref AWS::StackName
  MicroserviceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Name: !Ref ServiceName
        Cpu: !Ref ServiceCpu
        Essential: 'true'
        Image: !Ref ImageUrl
        Memory: !Ref ServiceMemory
        {{with .Environment}}
        Environment:
          {{range $key, $val := .}}
          - Name: {{$key}}
            Value: !Sub {{$val}}
          {{end}}
        {{end}}
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref AWS::StackName
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: container
        PortMappings:
        - HostPort: 0
          ContainerPort: !Ref ServicePort
      Volumes: []
      TaskRoleArn: !GetAtt EcsTaskRole.Arn
  EcsElbHttpListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HasElbHttpListener
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref EcsElbTargetGroup
      Conditions:
      - Field: path-pattern
        Values: !Ref PathPattern
      ListenerArn:
        Fn::ImportValue: !Sub ${EcsElbHttpListenerArn}
      Priority: !Ref ListenerRulePriority
  EcsElbHttpsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HasElbHttpsListener
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref EcsElbTargetGroup
      Conditions:
      - Field: path-pattern
        Values: !Ref PathPattern
      ListenerArn:
        Fn::ImportValue: !Sub ${EcsElbHttpsListenerArn}
      Priority: !Ref ListenerRulePriority
  EcsElbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: HasPathPattern
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref ServiceHealthEndpoint
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 3
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-299
      Port: !Ref ServicePort
      Protocol: HTTP
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: 60
      UnhealthyThresholdCount: 5
      VpcId:
        Fn::ImportValue: !Sub ${VpcId}
Outputs:
  MicroserviceTaskDefinition:
    Description: Roadmap Task Definition
    Value: !Ref MicroserviceTaskDefinition
  EcsCluster:
    Description: Roadmap Cluster
    Value:
      Fn::ImportValue: !Ref EcsCluster
