---

environments:
  - name: example

templates:
  mu-cluster-example:
    Resources:

      # Define a new security group
      ExtraSG:
        Type: AWS::EC2::SecurityGroup
        Properties:
          VpcId:
            Fn::ImportValue: !Sub ${VpcId}
          GroupDescription: Example additional ECS Host Security Group
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '8080'
            ToPort: '8080'
            CidrIp: !Ref SshAllow

      ## Update the existing launch config to reference new SG
      ContainerInstances:
        Properties:
          SecurityGroups: [ !Ref ExtraSG ]